### ISSUE TITLE
See referral traffic for inbound analysis

### ISSUE THREAD

**Issue by therealdylanmartin** [therealdylanmartin/collaboration-demo#1]
USER STORY:

AS A marketing analyst
I WANT to see referral traffic
SO THAT I can adapt strategy to convert more leads

ACCEPTANCE CRITERIA:

GIVEN I am an authenticated user
WHEN I request a range of referral traffic
THEN a chart is generated

**Comment by ohNOitsRO** [comment]
I fixed it boss

**Comment by ohNOitsRO** [comment]
We did it boys we fixed the internet
